library(modeest)
zipcode=read.csv("demographic-statistics-by-zip-code-1 (1).csv")
View(zipcode)
diamin=mean(zipcode$COUNT.PARTICIPANTS)
print(diamin)
avgvelr=mean(zipcode$COUNT.FEMALE)
print(avgvelr)
avddist=mean(zipcode$PERCENT.FEMALE)
print(avddist)
middist=median(zipcode$COUNT.MALE)
print(middist)
modemag=mfv(zipcode$PERCENT.MALE)
print(modemag)
sdofvelocity=var(zipcode$COUNT.GENDER.UNKNOWN)
print(sdofvelocity)
cgfthrange=max(zipcode$COUNT.FEMALE)-min(zipcode$COUNT.MALE)
print(range)

library(moments)
kurtosis(zipcode$COUNT.US.CITIZEN)
skewness(zipcode$COUNT.OTHER.CITIZEN.STATUS)